services:
  postgres:
    image: postgres:16
    container_name: nest-prisma-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_prisma_db
    ports:
      - "5432:5432"
    volumes:
      - nest_prisma_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ticketbox-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ticketbox_redis_data:/data
    command: redis-server --appendonly yes

volumes:
  nest_prisma_pg_data:
  ticketbox_redis_data:
