export const CELL_SIZE = 30;

export const DATE_RANGE_OPTIONS = {
    LAST_30_DAYS: "LAST_30_DAYS",
    PREVIOUS_MONTH: "PREVIOUS_MONTH",
    PREVIOUS_WEEK: "PREVIOUS_WEEK",
    THIS_MONTH: "THIS_MONTH",
    THIS_WEEK: "THIS_WEEK",
    CUSTOM: "CUSTOM",
};
